--- #YAML:1.0
name:                POE-Component-JobQueue
version:             0.56
abstract:            POE component for processing large numbers of tasks with finite numbers of workers.
license:             perl
author:              
    - Rocco Caputo <rcaputo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POE:                           0.31
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
