--- #YAML:1.0
name:                POE-Component-JobQueue
version:             0.55
abstract:            Handle large numbers of tasks with finite numbers of workers.
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
    POE:                           0.31
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
