# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-JobQueue
version:      0.54
version_from: JobQueue.pm
installdirs:  site
requires:
    POE:                           0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
