--- #YAML:1.0
name:               POE-Component-JobQueue
version:            0.571
abstract:           POE component for processing large numbers of tasks with finite numbers of workers.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:  1.007
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://thirdlobe.com/svn/poco-jobqueue/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
